one cookiecutter to rule them all
Pylons/pyramid-cookiecutter-starter pull request #61
Opened 2018-09-19 02:10 UTC by stloma

Merging of the ZODB and SQLAlchemy into this one.

2018-09-19 02:22 UTC, stevepiercy commented
Please sign https://github.com/Pylons/pyramid-cookiecutter-starter/blob/latest/CONTRIBUTORS.txt

I'll review in the next couple days.

2018-09-19 13:07 UTC, stevepiercy requested changes
This looks great. Only a couple of minor changes, then I'll run through the matrix of options.

2018-09-19 13:07 UTC, stevepiercy commented on hooks/post_gen_project.py
> +    Each backend has associated files in the cookiecutter, prefixed by it's
its

2018-09-19 13:07 UTC, stevepiercy commented on README.rst
> +A Cookiecutter (project template) for creating a Pyramid starter project using URL dispatch. Customizable options upon install are Jinja2, Chameleon, or Mako for templating and memory, SQLAlchemy, or
A Cookiecutter (project template) for creating a Pyramid starter project.
Customizable options upon install include choice of:
* template language (Jinja2, Chameleon, or Mako)
* persistent backend (none, SQLAlchemy with SQLite, or ZODB)
* mapping of URLs to routes (if selected persistent backend is "none" or "sqlalchemy" then URL dispatch, and if "zodb" then traversal)

2018-09-19 13:09 UTC, stevepiercy commented
Can we automate the build process across all the selected options of template language and persistent backend, for a total of 9 permutations? I don't know how to do that.

2018-09-20 00:57 UTC, stevepiercy approved these changes
Thank you! These changes are good. I still need to run through the 9 permutations.

2018-09-20 01:00 UTC, stloma commented
No rush :) I'll begin looking through the build process as well.

2018-09-21 08:59 UTC, stevepiercy requested changes
Spelling corrections

2018-09-21 08:59 UTC, stevepiercy commented on tests/test_it.py
> +    # this is a hook for executing scaffold tests against a specifick
specific

2018-09-21 08:59 UTC, stevepiercy commented on tests/test_it.py
> +    # this is a hook for executing scaffold tests against a specifick
specific

2018-09-21 12:53 UTC, stevepiercy commented
@mmerickel @stloma has worked through all the fun issues on Windows. I'd appreciate your review to find any improvements.

2018-09-21 13:04 UTC, stevepiercy approved these changes

2018-10-03 04:12 UTC, mmerickel approved these changes
this is wild but I think you've done it in a very clean and maintainable way +1

2018-10-05 09:35 UTC, merged

2018-10-05 09:36 UTC, stevepiercy commented
I'll deprecate the other CCs in their readmes on their master branches.