Fix Layout.pt
Pylons/pyramid-cookiecutter-starter pull request #72
Opened 2019-11-20 10:16 UTC by Druidmaciek

I noticed that in layout.pt HTML tag's lang attribute uses jinja2 syntax instead of chameleon syntax.

2019-11-20 18:59 UTC, stevepiercy requested changes
This PR should be made not against `latest`, but against `master`. Sorry for the confusion. All development occurs on `master`, and then we cut a release to `latest` and `1.10-branch` branches, backporting the changes.

After you make the PR to `master`, would you also please add a change note in CHANGES.txt?

Thank you for catching this and submitting a PR!

2019-11-20 18:59 UTC, stevepiercy commented on {{cookiecutter.repo_name}}/{{cookiecutter.repo_name}}/base_templates/layout.pt
> +<html lang="${ '{{request.locale_name}}' }">
I think you got the syntax inverted. Cookiecutter uses Jinja2 on the outer element to render the inner element.
```suggestion
<html lang="{{ '${request.locale_name}' }}">
```

2019-11-20 20:30 UTC, stevepiercy commented
Please make the PR against `master`. Then I can accept it. Thank you!

2019-12-24 22:17 UTC, mmerickel commented
@stevepiercy please turn this into a new PR if you don't mind and close this one or push the updates to it via https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/committing-changes-to-a-pull-request-branch-created-from-a-fork

2019-12-25 07:52 UTC, stevepiercy commented
Closing in favor of #73

2019-12-25 07:52 UTC, closed without merging